# Tutorial pulled from:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops
#
# This pipeline is essentially going to automatically build and push a docker image
# to our docker registry/repository.

# define the trigger
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu-16.04'

# Here are our build variables, whereas we can store more secret keys in the pipeline variables.
variables:
  dockerId: $env:dockerId    # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: $env:imageName  # Replace with the name of the image you want to publish

steps:
## Deploy the application
- script: |
    dotnet build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $env:dockerPassword
    docker push $(dockerId)/$(imageName)
 