# Tutorial pulled from:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops
#
# This pipeline is essentially going to automatically build and push a docker image
# to our docker registry/repository.

# define the trigger
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'Ubuntu-16.04'

# Here are our build variables, whereas we can store more secret keys in the pipeline variables.
variables:
  dockerId: driouxg    # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: water-pls-docker  # Replace with the name of the image you want to publish
  kubernetesCluster: dryoxCluster
  azureResourceGroup: dryoxResourceGroup

steps:
## Deploy the application
- script: |
    docker build -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $DOCKER_PASSWORD
    docker push $(dockerId)/$(imageName)
  env:
    DOCKER_PASSWORD: $(dockerPassword)

# Run a deployment using our Kubernetes Service, with our deplyoment file.
- task: Kubernetes@1
  displayName: kubectl apply using configFile
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: $AZURE_SUBSCRIPTION_ENDPOINT
    #azureSubscriptionEndpoint: dryoxclust-dryoxresourcegro-03d9d0-4d4c75b6.hcp.westus.azmk8s.io
    azureResourceGroup: $(azureResourceGroup)
    kubernetesCluster: $(kubernetesCluster)
    command: apply
    useConfigurationFile: true
    configuration: deployment-server.yaml
  env:
    AZURE_SUBSCRIPTION_ENDPOINT: $(azureSubscriptionEndpoint)